phone_book/contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.manage_contacts, name='manage_contacts'),
    path('<int:user_id>/update/', views.user_update, name='update'),
    path('create/', views.user_create, name='create'),
    path('<int:user_id>/', views.contact_detail, name='contact_detail'),
]

phone_book/phone_book/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('contact.urls', namespace='contact')),
    path('admin/', admin.site.urls),
]

phone_book/contact/models.py
from django.db import models
# from uuid import uuid4
# Create your models here.
class User(models.Model):

    # id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    id = models.AutoField(primary_key=True) # SERIAL PRIMARY KEY 
    username = models.CharField(max_length=100, null=False)
    email = models.CharField(max_length=100, null=True)
    mobile = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.username

phone_book/contact/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'mobile']
        widgets = {
            'email': forms.EmailInput(attrs={'type': 'email'}), 
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        return email
        

    def clean_mobile(self):
        mobile = self.cleaned_data['mobile']
        if not mobile.isdigit() or len(mobile) != 11:
            raise forms.ValidationError("Неверный формат номера телефона")
        return mobile

phone_book/contact/views.py
from django.shortcuts import redirect, render

# Create your views here.
from django.shortcuts import render
from django.http import Http404

from .forms import UserForm
from .models import User
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404
from .models import User
   

    
def manage_contacts(request):
    all_users = User.objects.all()
    if request.method == 'POST':
        message =''
        if 'action' in request.POST:
            action = request.POST['action']
            if action == 'delete':
                for user in all_users:
                    user.delete()
                message='Contacts deleted successfully!'
            context = {'message': message}
            template = 'result.html'
            return render(request, template, context)
    template = 'contacts.html'
    context = context = {'objects': all_users}
    return render(request, template, context)    
    
    
def contact_detail(request, user_id):
   
    if request.method == 'GET':
        try:
            entry = User.objects.get(id=user_id) 
        except User.DoesNotExist:
            message = 'Contact with this id doesn\'t exist'
            context = {'message': message}
            template = 'result.html'
            return render(request, template, context)
        context = {'contact': entry}
        template = 'contact_detail.html'
        return render(request, template, context)

    if request.method == 'POST':
        message =''
        if 'action' in request.POST:
            action = request.POST['action']
            if action == 'delete':
                try:
                    entry = User.objects.get(id=user_id) 
                    username = entry.username
                except User.DoesNotExist:
                    message = 'Contact with this id doesn\'t exist'
                else:
                    entry.delete()
                    message='Contact "'+ username + '" deleted successfully'
        context = {'message': message}
        template = 'result.html'
        return render(request, template, context)

    
def user_update(request, user_id):
    try:
        user = User.objects.get(id=user_id) 
        if request.method == 'POST':
            form = UserForm(request.POST, instance=user)  
            if form.is_valid():
                form.save()
                return redirect('contact:contact_detail', user.id)
        else:
            form = UserForm(instance=user)
    except User.DoesNotExist:
        message = 'Contact with this id doesn\'t exist'
        context = {'message': message}
        template = 'result.html'
        return render(request, template, context)
    context = {'contact': user, 'form': form}
    template = 'contact_form.html'
    return render(request, template, context)

def user_create(request):
    if request.method == 'POST':
        form = UserForm(request.POST)  
        if form.is_valid():
            user = form.save()
            return redirect('contact:contact_detail', user.id)
    else:
        form = UserForm()

    context = {'form': form}
    template = 'contact_form.html'
    return render(request, template, context)

def delete_all(request):
    all_users = User.objects.all()
    for user in all_users:
        user.delete()
    message='Contacts deleted successfully!'
    context = {'message': message}
    template = 'result.html'
    return render(request, template, context)

phone_book/contact/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contacts</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
    {% include "includes/header.html" %}
    <div class="container py-5">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

phone_book/contact/templates/contact_detail.html
{% extends 'base.html' %} 

{% block content %}
<div class="container my-4">
  <div class="row justify-content-center my-5 ">  
    <div class="card col-md-4 mb-3">
      <div class="card-body">
        <p class="card-text">Username: {{ contact.username }}</p>
        <p class="card-text">Email: {{ contact.email }}</p>
        <p class="card-text">Phone number: {{ contact.mobile }}</p>
        <div class="list-group list-group-horizontal">
          <span class="d-inline">
            <a class="btn btn-primary" href="{% url 'contact:update' contact.id %}">Edit</a>
          </span>
          <span class="d-inline mx-1">
            <form method="post" action="{% url 'contact:contact_detail' contact.id %}" class=" mx-1">
              {% csrf_token %} 
              <button type="submit" name="action" value="delete" class="btn btn-danger">Delete</button>
            </form>
          </span>
        </div>
      </div>
      <div class="mx-3 mb-4">
        <a class="" href="{% url 'contact:manage_contacts' %}">To contact list</a>
      </div>  
    </div>
  </div>
</div>
{% endblock %}

phone_book/contact/templates/contact_form.html
{% extends 'base.html' %} 
{% load django_bootstrap5 %}
{% block content %}
<div class="row justify-content-center my-5">  
  <div class="col-md-4 mb-3">
    <div class="card">
      <div class="card-body">
        {% with request.resolver_match.view_name as view_name %}
          {% if view_name  == 'contact:update' %}
            <h3 class="card-title">Edit contact</h3>
          {% elif view_name  == 'contact:create' %}
            <h3 class="card-title">Create contact</h3>
          {% endif %}
        {% endwith %}
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form  %}
          {% bootstrap_button button_type="submit" content="Сохранить" %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

phone_book/contact/templates/contacts.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-4">
  <div class="row justify-content-center">  
    <div class="col-md-7 mb-3">
      <div class="list-group list-group-horizontal">
        <div class="d-inline">
          <a class="btn btn-primary" href="{% url 'contact:create' %}">Add contact</a>
        </div>
        <div class="d-inline mx-3">
          {% if objects %}
            <form method="post" class="">
              {% csrf_token %} 
              <button type="submit" name="action" value="delete" class="btn btn-danger">Delete all contacts</button>
            </form>
          {% endif %}
        </div>
      </div>
    </div>
    {% for entry in objects %}
      <div class="col-md-7 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><a href="{% url 'contact:contact_detail' entry.id %}">{{ entry.username }}</a></h5>
            <p class="card-text">Email: {{ entry.email }}</p>
            <p class="card-text">Phone number: {{ entry.mobile }}</p>
          </div>
        </div>
      </div>
    {% endfor %}  
  </div>
</div>
{% endblock %}

phone_book/contact/templates/includes/header.html
<head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
    <div class="container">
      <a class="navbar-brand" href="{% url 'contact:manage_contacts' %}">
        Contact List ☎
      </a>  
    </div>
  </nav>
</head>

phone_book/contact/templates/result.html
{% extends 'base.html' %}

{% block content %}
  <h3 class="my-4">{{ message }}</h3>
{% endblock %}